modLoader="javafml"
loaderVersion="[41,)"
license="MIT"
issueTrackerURL="https://github.com/SilentChaos512/SilentLib"
displayURL="https://www.curseforge.com/minecraft/mc-mods/silent-lib"
#logoFile="examplemod.png"
credits="silentchaos512"
authors="SilentChaos512"

[[mods]]
    modId="silentlib"
    version="${file.jarVersion}"
    displayName="Silent Lib"
    updateJSONURL="https://raw.githubusercontent.com/SilentChaos512/SilentLib/1.19.x/update.json"
    description='''
    Shared library for Silent's mods
    '''

[[dependencies.silentlib]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.silentlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"